[tool.ruff]
exclude = [
    ".git",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "alembic/",
    "temp/",
]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9", "F",
    "I001",
    "I002",
]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[tool.pytest.ini_options]
addopts = "--cov-branch --cov-fail-under=65"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests/unit"]
asyncio_mode = "auto"
