"""Update User and Referral models

Revision ID: c848e75b3206
Revises: 6daca0ba417e
Create Date: 2025-03-31 12:11:18.368413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c848e75b3206'
down_revision: Union[str, None] = '6daca0ba417e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_table('game_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_tasks_game_name'), 'game_tasks', ['game_name'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('promo_code', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code')
    )
    op.create_index('ix_game_name_id', 'promo_codes', ['game_name', 'id'], unique=False)
    op.create_table('announcement_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=3500), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'language_code', name='uc_announcement_language')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.drop_table('user_logs')
    op.drop_index('ix_hide_ball_created_at', table_name='hide_ball')
    op.drop_index('ix_hide_ball_promo_code', table_name='hide_ball')
    op.drop_table('hide_ball')
    op.drop_index('ix_tile_trio_created_at', table_name='tile_trio')
    op.drop_index('ix_tile_trio_promo_code', table_name='tile_trio')
    op.drop_table('tile_trio')
    op.drop_index('ix_merge_away_created_at', table_name='merge_away')
    op.drop_index('ix_merge_away_promo_code', table_name='merge_away')
    op.drop_table('merge_away')
    op.drop_index('ix_stone_age_created_at', table_name='stone_age')
    op.drop_index('ix_stone_age_promo_code', table_name='stone_age')
    op.drop_table('stone_age')
    op.drop_index('ix_chain_cube_2048_created_at', table_name='chain_cube_2048')
    op.drop_index('ix_chain_cube_2048_promo_code', table_name='chain_cube_2048')
    op.drop_table('chain_cube_2048')
    op.drop_index('ix_cafe_dash_created_at', table_name='cafe_dash')
    op.drop_index('ix_cafe_dash_promo_code', table_name='cafe_dash')
    op.drop_table('cafe_dash')
    op.drop_index('ix_polysphere_created_at', table_name='polysphere')
    op.drop_index('ix_polysphere_promo_code', table_name='polysphere')
    op.drop_table('polysphere')
    op.drop_index('ix_infected_frontier_created_at', table_name='infected_frontier')
    op.drop_index('ix_infected_frontier_promo_code', table_name='infected_frontier')
    op.drop_table('infected_frontier')
    op.drop_index('ix_pin_out_master_created_at', table_name='pin_out_master')
    op.drop_index('ix_pin_out_master_promo_code', table_name='pin_out_master')
    op.drop_table('pin_out_master')
    op.drop_index('ix_bouncemasters_created_at', table_name='bouncemasters')
    op.drop_index('ix_bouncemasters_promo_code', table_name='bouncemasters')
    op.drop_table('bouncemasters')
    op.drop_index('ix_count_masters_created_at', table_name='count_masters')
    op.drop_index('ix_count_masters_promo_code', table_name='count_masters')
    op.drop_table('count_masters')
    op.drop_index('ix_zoopolis_created_at', table_name='zoopolis')
    op.drop_index('ix_zoopolis_promo_code', table_name='zoopolis')
    op.drop_table('zoopolis')
    op.drop_index('ix_mow_and_trim_created_at', table_name='mow_and_trim')
    op.drop_index('ix_mow_and_trim_promo_code', table_name='mow_and_trim')
    op.drop_table('mow_and_trim')
    op.drop_index('ix_twerk_race_3d_created_at', table_name='twerk_race_3d')
    op.drop_index('ix_twerk_race_3d_promo_code', table_name='twerk_race_3d')
    op.drop_table('twerk_race_3d')
    op.drop_index('ix_gangs_wars_created_at', table_name='gangs_wars')
    op.drop_index('ix_gangs_wars_promo_code', table_name='gangs_wars')
    op.drop_table('gangs_wars')
    op.drop_index('ix_train_miner_created_at', table_name='train_miner')
    op.drop_index('ix_train_miner_promo_code', table_name='train_miner')
    op.drop_table('train_miner')
    op.drop_index('ix_among_waterr_created_at', table_name='among_waterr')
    op.drop_index('ix_among_waterr_promo_code', table_name='among_waterr')
    op.drop_table('among_waterr')
    op.drop_index('ix_factory_world_created_at', table_name='factory_world')
    op.drop_index('ix_factory_world_promo_code', table_name='factory_world')
    op.drop_table('factory_world')
    op.drop_index('ix_fluff_crusade_created_at', table_name='fluff_crusade')
    op.drop_index('ix_fluff_crusade_promo_code', table_name='fluff_crusade')
    op.drop_table('fluff_crusade')
    op.add_column('users', sa.Column('last_request_datetime', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               nullable=False)
    op.alter_column('users', 'registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'total_keys_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'daily_requests_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('users_chat_id_key', 'users', type_='unique')
    op.drop_constraint('users_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'last_reset_date')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'notes')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'last_request_time')
    op.drop_column('users', 'preferred_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_request_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_reset_date', sa.DATE(), server_default=sa.text('(now())::date'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.create_unique_constraint('users_chat_id_key', 'users', ['chat_id'])
    op.alter_column('users', 'daily_requests_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_keys_generated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'registration_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'language_code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=False)
    op.drop_column('users', 'last_request_datetime')
    op.create_table('fluff_crusade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fluff_crusade_pkey')
    )
    op.create_index('ix_fluff_crusade_promo_code', 'fluff_crusade', ['promo_code'], unique=False)
    op.create_index('ix_fluff_crusade_created_at', 'fluff_crusade', ['created_at'], unique=False)
    op.create_table('factory_world',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='factory_world_pkey')
    )
    op.create_index('ix_factory_world_promo_code', 'factory_world', ['promo_code'], unique=False)
    op.create_index('ix_factory_world_created_at', 'factory_world', ['created_at'], unique=False)
    op.create_table('among_waterr',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='among_waterr_pkey')
    )
    op.create_index('ix_among_waterr_promo_code', 'among_waterr', ['promo_code'], unique=False)
    op.create_index('ix_among_waterr_created_at', 'among_waterr', ['created_at'], unique=False)
    op.create_table('train_miner',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='train_miner_pkey')
    )
    op.create_index('ix_train_miner_promo_code', 'train_miner', ['promo_code'], unique=False)
    op.create_index('ix_train_miner_created_at', 'train_miner', ['created_at'], unique=False)
    op.create_table('gangs_wars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gangs_wars_pkey')
    )
    op.create_index('ix_gangs_wars_promo_code', 'gangs_wars', ['promo_code'], unique=False)
    op.create_index('ix_gangs_wars_created_at', 'gangs_wars', ['created_at'], unique=False)
    op.create_table('twerk_race_3d',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='twerk_race_3d_pkey')
    )
    op.create_index('ix_twerk_race_3d_promo_code', 'twerk_race_3d', ['promo_code'], unique=False)
    op.create_index('ix_twerk_race_3d_created_at', 'twerk_race_3d', ['created_at'], unique=False)
    op.create_table('mow_and_trim',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mow_and_trim_pkey')
    )
    op.create_index('ix_mow_and_trim_promo_code', 'mow_and_trim', ['promo_code'], unique=False)
    op.create_index('ix_mow_and_trim_created_at', 'mow_and_trim', ['created_at'], unique=False)
    op.create_table('zoopolis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='zoopolis_pkey')
    )
    op.create_index('ix_zoopolis_promo_code', 'zoopolis', ['promo_code'], unique=False)
    op.create_index('ix_zoopolis_created_at', 'zoopolis', ['created_at'], unique=False)
    op.create_table('count_masters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='count_masters_pkey')
    )
    op.create_index('ix_count_masters_promo_code', 'count_masters', ['promo_code'], unique=False)
    op.create_index('ix_count_masters_created_at', 'count_masters', ['created_at'], unique=False)
    op.create_table('bouncemasters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bouncemasters_pkey')
    )
    op.create_index('ix_bouncemasters_promo_code', 'bouncemasters', ['promo_code'], unique=False)
    op.create_index('ix_bouncemasters_created_at', 'bouncemasters', ['created_at'], unique=False)
    op.create_table('pin_out_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pin_out_master_pkey')
    )
    op.create_index('ix_pin_out_master_promo_code', 'pin_out_master', ['promo_code'], unique=False)
    op.create_index('ix_pin_out_master_created_at', 'pin_out_master', ['created_at'], unique=False)
    op.create_table('infected_frontier',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='infected_frontier_pkey')
    )
    op.create_index('ix_infected_frontier_promo_code', 'infected_frontier', ['promo_code'], unique=False)
    op.create_index('ix_infected_frontier_created_at', 'infected_frontier', ['created_at'], unique=False)
    op.create_table('polysphere',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='polysphere_pkey')
    )
    op.create_index('ix_polysphere_promo_code', 'polysphere', ['promo_code'], unique=False)
    op.create_index('ix_polysphere_created_at', 'polysphere', ['created_at'], unique=False)
    op.create_table('cafe_dash',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cafe_dash_pkey')
    )
    op.create_index('ix_cafe_dash_promo_code', 'cafe_dash', ['promo_code'], unique=False)
    op.create_index('ix_cafe_dash_created_at', 'cafe_dash', ['created_at'], unique=False)
    op.create_table('chain_cube_2048',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chain_cube_2048_pkey')
    )
    op.create_index('ix_chain_cube_2048_promo_code', 'chain_cube_2048', ['promo_code'], unique=False)
    op.create_index('ix_chain_cube_2048_created_at', 'chain_cube_2048', ['created_at'], unique=False)
    op.create_table('stone_age',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stone_age_pkey')
    )
    op.create_index('ix_stone_age_promo_code', 'stone_age', ['promo_code'], unique=False)
    op.create_index('ix_stone_age_created_at', 'stone_age', ['created_at'], unique=False)
    op.create_table('merge_away',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='merge_away_pkey')
    )
    op.create_index('ix_merge_away_promo_code', 'merge_away', ['promo_code'], unique=False)
    op.create_index('ix_merge_away_created_at', 'merge_away', ['created_at'], unique=False)
    op.create_table('tile_trio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tile_trio_pkey')
    )
    op.create_index('ix_tile_trio_promo_code', 'tile_trio', ['promo_code'], unique=False)
    op.create_index('ix_tile_trio_created_at', 'tile_trio', ['created_at'], unique=False)
    op.create_table('hide_ball',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hide_ball_pkey')
    )
    op.create_index('ix_hide_ball_promo_code', 'hide_ball', ['promo_code'], unique=False)
    op.create_index('ix_hide_ball_created_at', 'hide_ball', ['created_at'], unique=False)
    op.create_table('user_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_logs_pkey')
    )
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('announcement_translations')
    op.drop_index('ix_game_name_id', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_game_tasks_game_name'), table_name='game_tasks')
    op.drop_table('game_tasks')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
