name: CI workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          python-version: "3.12.2"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
